name: nodejs-pkg-version-action
author: Jan Tietze
description: Outputs the version number from a package.json
inputs:
  path:
    description: "Path to package.json"
    required: true
    default: "./package.json"
outputs:
  version:
    description: "Version from package.json"
runs:
  using: "node12"
  main: "dist/index.js"
